
import { UserRole, Language, Priority, Module, DepartmentModality, RoomModality, RoomStatus, ClinicStatus, PayerType } from './types';

export const translations = {
  [Language.EN]: {
    appName: 'MedMIS Core 2.0',
    role: 'Role',
    language: 'Language',
    unauthorized: 'Unauthorized Access',
    date: 'Date',
    time: 'Time',
    room: 'Room',
    modality: 'Modality',
    availability: 'Availability',
    bookAppointment: 'Book Appointment',
    book: 'Book',
    patientName: 'Patient Name',
    complaints: 'Complaints / Reason',
    priority: 'Priority',
    urgent: 'Urgent (SR)',
    standard: 'Standard (STD)',
    planned: 'Planned (PLN)',
    close: 'Close',
    selectSlot: 'Select a Slot to Book',
    bookingSuccessful: 'Booking Successful. Please confirm details with reception.',
    bookingFailed: 'Booking Failed. Please try again.',
    status: 'Status',
    actions: 'Actions',
    waiting: 'Waiting',
    inProgress: 'In Progress',
    done: 'Done',
    cancelled: 'Cancelled',
    summarize: 'Summarize with AI',
    summary: 'AI Summary',
    generatingSummary: 'Generating summary...',
    noSlots: 'No available slots for this day.',
    noQueue: 'No patients in the queue for this day.',
    slotsFor: 'Available Slots for',
    patientsQueue: "Today's Patient Queue",
    logout: 'Logout',
    
    // New Reception Module Keys
    "reception.title": "Add Patient to Queue",
    "reception.scanQr": "Scan QR Code",
    "reception.scanQrTitle": "Scan or Enter QR Code",
    "reception.qrInputLabel": "QR Code or DeepLink",
    "reception.qrSubmit": "Find Referral",
    "reception.fullName": "Full Name",
    "reception.age": "Age",
    "reception.phone": "Phone",
    "reception.address": "Address",
    "reception.referrer": "Referrer Doctor (optional)",
    "reception.room": "Room / Cabinet",
    "reception.service": "Service / Procedure",
    "reception.priority": "Priority",
    "reception.priority.sr": "Urgent (≈15 min)",
    "reception.priority.std": "Standard (≈2 hours)",
    "reception.priority.pln": "Planned (≈24 hours)",
    "reception.complaints": "Complaints / Notes",
    "reception.attachments": "Attachments",
    "reception.addToQueue": "Add to Queue",
    "reception.today": "Today",
    "reception.periods": "Next 3 / 7 / 30 days",
    "reception.otherRooms": "Other rooms in clinic",
    "reception.left": "{{left}} of {{capacity}} left",
    "reception.book": "Book",
    "reception.reschedule": "Reschedule",
    "reception.cancel": "Cancel",
    "reception.availableSlotsInfo": "Showing available slots and occupancy",
    "reception.selectRoomPrompt": "Select a room to see available slots",
    "reception.days3": "3 Days",
    "reception.days7": "7 Days",
    "reception.days30": "30 Days",
    "reception.loading": "Loading...",
    "reception.noSlotsForPeriod": "No available slots for the selected period.",
    "reception.workload": "Workload",
    
    // MRT Module Keys
    "mrt.title": "MRT/CT Room",
    "mrt.todayQueue": "Today's Queue",
    "mrt.start": "Start",
    "mrt.attach": "Attach Files",
    "mrt.complete": "Complete Study",
    "mrt.noShow": "No-show",
    "mrt.reschedule": "Reschedule",
    "mrt.reassign": "Reassign",
    "mrt.upload.title": "Upload Files",
    "mrt.upload.addDicom": "Add DICOM Link",
    "mrt.upload.addDoc": "Add Document Link",
    "mrt.upload.count": "{{count}} files attached",
    "mrt.upload.totalSize": "Total size: {{size}} MB",
    "mrt.upload.fileName": "File Name/URL",
    "mrt.upload.fileSize": "Size (MB)",
    "mrt.upload.fileType": "Type",
    "mrt.upload.add": "Add",
    "mrt.room": "Room",
    "mrt.slot": "Slot",
    "mrt.status.in_progress": "In progress",
    "mrt.status.uploaded": "Uploaded",
    "mrt.status.finished": "Finished",
    "mrt.openRad": "Open in Radiology",
    "mrt.selectRoom": "Select a Room",
    "mrt.noPatients": "No patients scheduled for this room today.",

    // Radiology Workbench Keys
    "radiology.inbox": "Radiology Inbox",
    "radiology.studyDetails": "Study Details",
    "radiology.selectStudy": "Select a study from the inbox to view details.",
    "radiology.patientInfo": "Patient Information",
    "radiology.maskedName": "Patient ID",
    "radiology.age": "Age",
    "radiology.priority": "Priority",
    "radiology.complaints": "Complaints",
    "radiology.assignedTo": "Assigned To",
    "radiology.dicomFiles": "DICOM Files",
    "radiology.documents": "Documents",
    "radiology.noFiles": "No files uploaded for this category.",
    "radiology.viewFile": "View",
    "radiology.uploadedOn": "Uploaded on",
    "radiology.status": "Status",

    // Referrer Portal Keys
    "ref.create": "Create Referral",
    "ref.myReferrals": "My Referrals",
    "ref.patientHint": "Patient / Complaint",
    "ref.qrCode": "QR Code",
    "ref.shortCode": "Short Code",
    "ref.createdAt": "Created At",
    "ref.status": "Status",
    "ref.share": "Share",
    "ref.copy": "Copy",
    "ref.copied": "Copied!",
    "ref.status.yellow": "Waiting",
    "ref.status.green": "Completed",
    "ref.status.red": "Expired",
    "ref.all": "All",
    "ref.noReferrals": "You have not created any referrals yet.",
    "ref.createReferralFor": "Create Referral for",
    "ref.patientInitials": "Patient Initials",
    "ref.complaint": "Complaint",
    
    // Patient App
    "pat.myBookings": "My Appointments",
    "pat.myReports": "My Reports",
    "pat.selfBooking": "Book a Visit",
    "pat.pay": "Pay",
    "pat.reschedule": "Reschedule",
    "pat.cancel": "Cancel",
    "pat.openChat": "Open Chat",
    "pat.viewReport": "View Report",
    "pat.download": "Download",
    "pat.status.booked": "Booked",
    "pat.status.paid": "Paid",
    "pat.status.done": "Completed",
    "pat.status.cancelled": "Cancelled",
    "pat.noBookings": "You have no appointments.",
    "pat.noReports": "You have no reports available.",
    "pat.selfBookDiscount": "Save 20% by booking online!",

    // Manager Panel
    "mgr.kpis": "Key Performance Indicators",
    "mgr.queues": "Patient Queues",
    "mgr.schedules": "Schedules",
    "mgr.assign": "Assign",
    "mgr.reassign": "Reassign",
    "mgr.escalate": "Escalate",
    "mgr.slaCompliance": "SLA Compliance",
    "mgr.avgWaitTime": "Avg. Wait Time",
    "mgr.radLoad": "Radiologist Workload",
    "mgr.unassigned": "Unassigned",
    "mgr.assignedTo": "Assigned To",
    "mgr.radiologist": "Radiologist",
    "mgr.assignRadiologistTitle": "Assign Radiologist",
    "mgr.selectRadiologist": "Select a radiologist",
    "mgr.escalationSuccess": "Priority escalated successfully.",
    "mgr.assignSuccess": "Radiologist assigned successfully.",
    "mgr.noQueuedItems": "No active items in the queue.",

    // Finance Module
    "fin.title": "Clinic Finance",
    "fin.totalCharged": "Total Charged",
    "fin.totalPaid": "Total Paid Out",
    "fin.currentDebts": "Current Debts",
    "fin.chargeByRole": "Charge Distribution by Role",
    "fin.statementRegistry": "Statement Registry",
    "fin.makePayout": "Make Payout",
    "fin.exportCsv": "Export CSV",
    "fin.service": "Service / Rule",
    "fin.creditedTo": "Credited To",
    "fin.amount": "Amount",
    "fin.date": "Date",
    "general.finances": "Finances", 

    // SuperAdmin Module
    "sa.overview": "System Overview",
    "sa.forecasts": "Forecasts",
    "sa.policies": "System Policies",
    "sa.totalPatients": "Total Patients Today",
    "sa.systemRevenue": "System Revenue",
    "sa.avgRadLoad": "Avg. Radiologist Load",
    "sa.activeUsers": "Active Users",
    "sa.nextMonthRevenue": "Next Month Revenue",
    "sa.patientGrowth": "Patient Growth",
    "sa.policyName": "Policy Name",
    "sa.value": "Value",
    "sa.apply": "Apply Changes",
    "sa.broadcast": "Broadcast Update",
    "sa.changesApplied": "Changes applied successfully!",

    // Rules Engine Module
    "rules.integrations": "Integrations",
    "rules.queue": "Queue Logic",
    "rules.sla": "SLA Policy",
    "rules.validate": "Validate JSON",
    "rules.apply": "Apply Changes",
    "rules.valid": "JSON is valid.",
    "rules.invalid": "Invalid JSON:",
    "rules.saved": "Rule saved successfully!",
    "rules.editorTitle": "Rule Content (JSON)",

    // Bonus & SLA Module
    "bonus.slaTimings": "SLA Target Timings",
    "bonus.bonusRules": "Bonus Point Rules",
    "bonus.dryRun": "Dry-run & Simulation",
    "bonus.targetMinutes": "Target (Minutes)",
    "bonus.points": "Points",
    "bonus.splits": "Splits",
    "bonus.runSimulation": "Run Simulation",
    "bonus.simulationResults": "Simulation Results",
    "bonus.affectedItems": "Affected Items",
    "bonus.totalBonusChange": "Total Bonus Change",
    "bonus.potentialBreaches": "Potential New Breaches",
    "bonus.previousTotal": "Previous Total",
    "bonus.newTotal": "New Total",
    "bonus.saveChanges": "Save Changes",
    "bonus.settingsUpdated": "Settings updated successfully!",

    // Language Manager Module
    "langMgr.key": "Key",
    "langMgr.save": "Save Changes",
    "langMgr.checkCoverage": "Check Coverage",
    "langMgr.import": "Import JSON",
    "langMgr.export": "Export JSON",
    "langMgr.coverageReport": "Coverage Report",
    "langMgr.totalKeys": "Total Unique Keys",
    "langMgr.keys": "keys",
    "langMgr.missingKeys": "Missing Keys",
    "langMgr.noMissing": "All keys present.",
    "langMgr.changesSaved": "Changes saved successfully!",

    // RBAC Module
    "rbac.userManagement": "User Management",
    "rbac.permissionManagement": "Permission Management",
    "rbac.user": "User",
    "rbac.email": "Email",
    "rbac.roles": "Roles",
    "rbac.manageRoles": "Manage Roles",
    "rbac.permission": "Permission",
    "rbac.enabled": "Enabled",
    "rbac.feature": "Feature",
    "rbac.canUseAiSummary": "Can use AI Summary",
    "rbac.canManageDicomPolicies": "Can manage DICOM policies",
    "rbac.canUploadDicom": "Can upload DICOM/docs",
    "rbac.canViewDicom": "Can view DICOM/docs",
    "rbac.canAccessMedRep": "Can access MedRep Interface",
    "rbac.canAccessClinicAdmin": "Can access Clinic Admin", // New permission translation
    "rbac.canManageRooms": "Can manage Rooms & Schedules", // New permission translation
    "rbac.canManageTariffs": "Can manage Tariffs & Contracts", // New permission translation
    "rbac.canManageClinicSettings": "Can manage Clinic Settings", // New permission translation
    "rbac.changesSaved": "Changes saved successfully.",

    // DICOM Hub Module
    "dicomhub.title": "DICOM Hub",
    "dicomhub.studyFiles": "Study Files",
    "dicomhub.accessPolicies": "Access Policies",
    "dicomhub.studyIdInput": "Enter Study ID",
    "dicomhub.fileList": "Files for Study {{studyId}}",
    "dicomhub.fileName": "File Name",
    "dicomhub.fileType": "Type",
    "dicomhub.fileSize": "Size (MB)",
    "dicomhub.uploadedAt": "Uploaded At",
    "dicomhub.signedUrl": "Signed URL",
    "dicomhub.status": "Status",
    "dicomhub.uploadFile": "Upload File",
    "dicomhub.revokeLink": "Revoke Link",
    "dicomhub.uploadNewFile": "Upload New File",
    "dicomhub.policySaved": "Policies saved successfully!",
    "dicomhub.noFiles": "No files found for this study.",
    "dicomhub.noPolicies": "No policies defined.",
    "dicomhub.role": "Role",
    "dicomhub.canView": "Can View",
    "dicomhub.canUpload": "Can Upload",
    "dicomhub.savePolicies": "Save Policies",
    "dicomhub.linkRevoked": "Link Revoked",
    "dicomhub.uploadSuccess": "File uploaded successfully!",
    "dicomhub.uploadError": "Error uploading file.",
    "dicomhub.revokeConfirm": "Are you sure you want to revoke this link? This action cannot be undone.",
    "dicomhub.revokeSuccess": "Link revoked successfully!",
    "dicomhub.revokeError": "Error revoking link.",
    "dicomhub.fileUrl": "URL файла", // Used for signedUrl column header
    "dicomhub.view": "View",
    "dicomhub.active": "Active",
    "dicomhub.revoked": "Revoked",
    "dicomhub.uploadDicom": "Upload DICOM",
    "dicomhub.uploadDocument": "Upload Document",

    // MedRep Interface Module
    "medrep.title": "MedRep Interface",
    "medrep.overview": "Overview",
    "medrep.kpis": "Key Performance Indicators",
    "medrep.referralFunnel": "Referral Funnel",
    "medrep.planFact": "Plan / Actual",
    "medrep.tasks": "Tasks",
    "medrep.chats": "Chats",
    "medrep.addTask": "Add Task",
    "medrep.completeTask": "Complete",
    "medrep.openChat": "Open Chat",
    "medrep.newTaskTitle": "Task Title",
    "medrep.dueDate": "Due Date",
    "medrep.clinic": "Related Clinic (Optional)",
    "medrep.noKpis": "No KPI data available for this period.",
    "medrep.noTasks": "No tasks for this medical representative.",
    "medrep.noChats": "No active chats.",
    "medrep.taskStatus.todo": "To Do",
    "medrep.taskStatus.doing": "Doing",
    "medrep.taskStatus.done": "Done",
    "medrep.taskAddedSuccess": "Task added successfully!",
    "medrep.taskUpdatedSuccess": "Task updated successfully!",
    "medrep.taskActionError": "Error performing task action.",
    "medrep.chatTopic": "Chat Topic",
    "medrep.lastMessage": "Last Message",
    "medrep.sendMessage": "Send Message",
    "medrep.chatInputPlaceholder": "Type your message...",
    "medrep.noMessages": "No messages in this chat yet.",
    "medrep.chatPanelTitle": "Chat with {{topic}}",
    "medrep.selectChatPrompt": "Select a chat to view messages.",
    "medrep.newChatPrompt": "Create new chat",

    // Clinic Module
    "clinic.title": "Clinic Management",
    "clinic.clinics": "Clinics",
    "clinic.rooms": "Rooms & Schedules",
    "clinic.tariffs": "Tariffs & Contracts",
    "clinic.settings": "Settings",
    "clinic.createClinic": "Create Clinic",
    "clinic.editClinic": "Edit Clinic",
    "clinic.suspendClinic": "Suspend Clinic",
    "clinic.name": "Clinic Name",
    "clinic.code": "Code",
    "clinic.address": "Address",
    "clinic.phones": "Phones",
    "clinic.email": "Email",
    "clinic.geo": "Geo Location",
    "clinic.status": "Status",
    "clinic.createdAt": "Created At",
    "clinic.active": "Active",
    "clinic.suspended": "Suspended",
    "clinic.noClinics": "No clinics found.",
    "clinic.selectClinic": "Select a Clinic",
    "clinic.addPhone": "Add Phone",
    "clinic.today": "Today",
    "clinic.horizon": "Horizon (3/7/30 Days)",
    "clinic.compare": "Compare Rooms",
    "clinic.roomName": "Room Name",
    "clinic.modality": "Modality",
    "clinic.deviceIds": "Devices",
    "clinic.capacityPerHour": "Capacity / Hour",
    "clinic.workHours": "Work Hours",
    "clinic.tags": "Tags",
    "clinic.addRoom": "Add Room",
    "clinic.editRoom": "Edit Room",
    "clinic.roomStatus": "Room Status",
    "clinic.status.up": "Up",
    "clinic.status.down": "Down",
    "clinic.status.maintenance": "Maintenance",
    "clinic.nextServiceAt": "Next Service At",
    "clinic.addSlot": "Add Slot",
    "clinic.editWorkHours": "Edit Work Hours",
    "clinic.setBlackout": "Set Blackout",
    "clinic.removeBlackout": "Remove Blackout",
    "clinic.capacity": "Capacity",
    "clinic.booked": "Booked",
    "clinic.free": "Free",
    "clinic.loadPct": "Load %",
    "clinic.noSchedules": "No schedule found for this day.",
    "clinic.saveCapacity": "Save Capacity",
    "clinic.selectPeriod": "Select Period",
    "clinic.avgLoadPct": "Avg. Load %",
    "clinic.totalBooked": "Total Booked",
    "clinic.totalCapacity": "Total Capacity",
    "clinic.noCompareData": "No comparison data available.",
    "clinic.tariffTitle": "Service Title",
    "clinic.serviceCode": "Service Code",
    "clinic.price": "Price",
    "clinic.currency": "Currency",
    "clinic.effectiveFrom": "Effective From",
    "clinic.effectiveTo": "Effective To",
    "clinic.addTariff": "Add Tariff",
    "clinic.editTariff": "Edit Tariff",
    "clinic.archiveTariff": "Archive Tariff",
    "clinic.noTariffs": "No tariffs found.",
    "clinic.contractPayer": "Payer",
    "clinic.contractValidFrom": "Valid From",
    "clinic.contractValidTo": "Valid To",
    "clinic.addContract": "Add Contract",
    "clinic.editContract": "Edit Contract",
    "clinic.noContracts": "No contracts found.",
    "clinic.policyName": "Policy Name",
    "clinic.policyValue": "Value",
    "clinic.policyDescription": "Description",
    "clinic.saveSettings": "Save Settings",
    "clinic.settingsSaved": "Settings saved successfully!",
    "clinic.blackoutReason": "Reason for Blackout",
    "clinic.blackoutStart": "Start Time",
    "clinic.blackoutEnd": "End Time",
    "clinic.confirmDelete": "Are you sure you want to delete this?",
    "clinic.clinicCreatedSuccess": "Clinic created successfully!",
    "clinic.clinicUpdatedSuccess": "Clinic updated successfully!",
    "clinic.clinicSuspendedSuccess": "Clinic status updated successfully!",
    "clinic.roomCreatedSuccess": "Room created successfully!",
    "clinic.roomUpdatedSuccess": "Room updated successfully!",
    "clinic.roomStatusUpdatedSuccess": "Room status updated successfully!",
    "clinic.slotAddedSuccess": "Slots added successfully!",
    "clinic.blackoutAddedSuccess": "Blackout period added successfully!",
    "clinic.blackoutRemovedSuccess": "Blackout removed successfully!",
    "clinic.tariffCreatedSuccess": "Tariff created successfully!",
    "clinic.tariffUpdatedSuccess": "Tariff updated successfully!",
    "clinic.contractCreatedSuccess": "Contract created successfully!",
    "clinic.contractUpdatedSuccess": "Contract updated successfully!",
    "clinic.errorFetching": "Error fetching data.",
    "clinic.errorSaving": "Error saving data.",
    "clinic.overlappingSlotsError": "Overlapping slots detected. Please adjust.",


    // Queue Statuses
    queued: 'Queued',
    in_progress: 'In Progress',
    described: 'Described',
    no_show: 'No-show',
    
    // Roles - Moved into a nested 'roles' object to avoid top-level key collisions
    roles: {
      [UserRole.SuperAdmin]: 'SuperAdmin',
      [UserRole.Admin]: 'Admin',
      [UserRole.Manager]: 'Manager',
      [UserRole.Radiologist]: 'Radiologist',
      [UserRole.Referrer]: 'Referrer',
      [UserRole.Patient]: 'Patient',
      [UserRole.Finance]: 'Finance',
      [UserRole.MrtOperator]: 'MRT Operator',
      [UserRole.Reception]: 'Reception',
      [UserRole.MedRep]: 'Medical Representative',
      [UserRole.ClinicAdmin]: 'Clinic Admin', // New role translation
    },

    // Modalities
    [RoomModality.MRI]: "MRI",
    [RoomModality.CT]: "CT",
    [RoomModality.XRAY]: "X-Ray",
    [RoomModality.US]: "US",

    // Room Statuses
    [RoomStatus.Up]: "Up",
    [RoomStatus.Down]: "Down",
    [RoomStatus.Maintenance]: "Maintenance",

    // Clinic Statuses
    [ClinicStatus.Active]: "Active",
    [ClinicStatus.Suspended]: "Suspended",

    // Payer Types
    [PayerType.Self]: "Self-Pay",
    [PayerType.Insurance]: "Insurance",
    [PayerType.Corporate]: "Corporate",


    // Modules
    [Module.ReceptionQueue]: 'Reception & Queue',
    [Module.MrtRoom]: 'MRT Room Service',
    [Module.RadiologyWorkbench]: 'Radiology Workbench',
    [Module.ReferrerPortal]: 'Referrer Portal',
    [Module.PatientApp]: 'Patient App Gateway',
    [Module.ManagerPanel]: 'Manager Panel',
    [Module.ClinicFinance]: 'Clinic Finance',
    [Module.SuperAdmin]: 'SuperAdmin Dashboard',
    [Module.RoleAccess]: 'Role & Access Manager',
    [Module.RulesEngine]: 'Rules Engine',
    [Module.BonusSla]: 'Bonus & SLA Control',
    [Module.LanguageManager]: 'Language Manager',
    [Module.ModuleConstructor]: 'Module Constructor',
    [Module.TestSandbox]: 'Test Sandbox',
    [Module.DicomHub]: 'DICOM Hub',
    [Module.MedRepInterface]: 'MedRep Interface',
    [Module.Clinic]: 'Clinic Management', // New module translation
  },
  [Language.RU]: {
    appName: 'MedMIS Ядро 2.0',
    role: 'Роль',
    language: 'Язык',
    unauthorized: 'Нет доступа',
    date: 'Дата',
    time: 'Время',
    room: 'Кабинет',
    modality: 'Модальность',
    availability: 'Доступность',
    bookAppointment: 'Записать на прием',
    book: 'Записать',
    patientName: 'Имя пациента',
    complaints: 'Жалобы / Причина',
    priority: 'Приоритет',
    urgent: 'Срочно (SR)',
    standard: 'Стандарт (STD)',
    planned: 'Планово (PLN)',
    close: 'Закрыть',
    selectSlot: 'Выберите слот для записи',
    bookingSuccessful: 'Запись прошла успешно! Подтвердите детали на ресепшене.',
    bookingFailed: 'Ошибка записи. Пожалуйста, попробуйте снова.',
    status: 'Статус',
    actions: 'Действия',
    waiting: 'Ожидает',
    inProgress: 'В процессе',
    done: 'Завершено',
    cancelled: 'Отменено',
    summarize: 'Суммаризировать с ИИ',
    summary: 'Сводка ИИ',
    generatingSummary: 'Генерация сводки...',
    noSlots: 'Нет доступных слотов на этот день.',
    noQueue: 'Нет пациентов в очереди на этот день.',
    slotsFor: 'Доступные слоты на',
    patientsQueue: "Сегодняшняя очередь пациентов",
    logout: 'Выйти',

    // New Reception Module Keys
    "reception.title": "Добавить пациента в очередь",
    "reception.scanQr": "Сканировать QR",
    "reception.scanQrTitle": "Сканировать или ввести QR-код",
    "reception.qrInputLabel": "QR-код или ссылка",
    "reception.qrSubmit": "Найти направление",
    "reception.fullName": "Полное имя",
    "reception.age": "Возраст",
    "reception.phone": "Телефон",
    "reception.address": "Адрес",
    "reception.referrer": "Направляющий врач (необязательно)",
    "reception.room": "Кабинет",
    "reception.service": "Услуга / Процедура",
    "reception.priority": "Приоритет",
    "reception.priority.sr": "Срочно (≈15 мин)",
    "reception.priority.std": "Стандарт (≈2 часа)",
    "reception.priority.pln": "Планово (≈24 часа)",
    "reception.complaints": "Жалобы / Заметки",
    "reception.attachments": "Вложения",
    "reception.addToQueue": "Добавить в очередь",
    "reception.today": "Сегодня",
    "reception.periods": "Ближайшие 3 / 7 / 30 дней",
    "reception.otherRooms": "Другие кабинеты клиники",
    "reception.left": "Осталось {{left}} из {{capacity}}",
    "reception.book": "Записать",
    "reception.reschedule": "Перенести",
    "reception.cancel": "Отменить",
    "reception.availableSlotsInfo": "Отображение доступных слотов и загруженности",
    "reception.selectRoomPrompt": "Выберите кабинет, чтобы увидеть доступные слоты",
    "reception.days3": "3 дня",
    "reception.days7": "7 дней",
    "reception.days30": "30 дней",
    "reception.loading": "Загрузка...",
    "reception.noSlotsForPeriod": "Нет доступных слотов на выбранный период.",
    "reception.workload": "Загруженность",
    
    // MRT Module Keys
    "mrt.title": "Кабинет МРТ/КТ",
    "mrt.todayQueue": "Сегодняшняя очередь",
    "mrt.start": "Начать",
    "mrt.attach": "Прикрепить файлы",
    "mrt.complete": "Завершить исследование",
    "mrt.noShow": "Неявка",
    "mrt.reschedule": "Перенести",
    "mrt.reassign": "Переназначить",
    "mrt.upload.title": "Загрузить файлы",
    "mrt.upload.addDicom": "Добавить DICOM",
    "mrt.upload.addDoc": "Добавить документ",
    "mrt.upload.count": "Прикреплено {{count}} файлов",
    "mrt.upload.totalSize": "Общий размер: {{size}} МБ",
    "mrt.upload.fileName": "Имя файла/URL",
    "mrt.upload.fileSize": "Размер (МБ)",
    "mrt.upload.fileType": "Тип",
    "mrt.upload.add": "Добавить",
    "mrt.room": "Кабинет",
    "mrt.slot": "Слот",
    "mrt.status.in_progress": "В процессе",
    "mrt.status.uploaded": "Загружено",
    "mrt.status.finished": "Завершено",
    "mrt.openRad": "Открыть в АРМ",
    "mrt.selectRoom": "Выберите кабинет",
    "mrt.noPatients": "На сегодня в этом кабинете нет пациентов.",
    
    // Radiology Workbench Keys
    "radiology.inbox": "АРМ Радиолога",
    "radiology.studyDetails": "Детали исследования",
    "radiology.selectStudy": "Выберите исследование из списка для просмотра деталей.",
    "radiology.patientInfo": "Информация о пациенте",
    "radiology.maskedName": "ID Пациента",
    "radiology.age": "Возраст",
    "radiology.priority": "Приоритет",
    "radiology.complaints": "Жалобы",
    "radiology.assignedTo": "Назначено",
    "radiology.dicomFiles": "DICOM файлы",
    "radiology.documents": "Документы",
    "radiology.noFiles": "Файлы не загружены в этой категории.",
    "radiology.viewFile": "Просмотр",
    "radiology.uploadedOn": "Загружено",
    "radiology.status": "Статус",
    
    // Referrer Portal Keys
    "ref.create": "Создать направление",
    "ref.myReferrals": "Мои направления",
    "ref.patientHint": "Пациент / Жалоба",
    "ref.qrCode": "QR-код",
    "ref.shortCode": "Короткий код",
    "ref.createdAt": "Создано",
    "ref.status": "Статус",
    "ref.share": "Поделиться",
    "ref.copy": "Копировать",
    "ref.copied": "Скопировано!",
    "ref.status.yellow": "Ожидание",
    "ref.status.green": "Завершено",
    "ref.status.red": "Просрочено",
    "ref.all": "Все",
    "ref.noReferrals": "Вы еще не создали ни одного направления.",
    "ref.createReferralFor": "Создать направление для",
    "ref.patientInitials": "Инициалы пациента",
    "ref.complaint": "Жалоба",

    // Patient App
    "pat.myBookings": "Мои записи",
    "pat.myReports": "Мои результаты",
    "pat.selfBooking": "Записаться на прием",
    "pat.pay": "Оплатить",
    "pat.reschedule": "Перенести",
    "pat.cancel": "Отменить",
    "pat.openChat": "Открыть чат",
    "pat.viewReport": "Смотреть отчет",
    "pat.download": "Скачать",
    "pat.status.booked": "Записан",
    "pat.status.paid": "Оплачено",
    "pat.status.done": "Завершено",
    "pat.status.cancelled": "Отменено",
    "pat.noBookings": "У вас нет записей.",
    "pat.noReports": "У вас нет доступных отчетов.",
    "pat.selfBookDiscount": "Сэкономьте 20% при онлайн-записи!",
    
    // Manager Panel
    "mgr.kpis": "Ключевые показатели",
    "mgr.queues": "Очереди пациентов",
    "mgr.schedules": "Расписания",
    "mgr.assign": "Назначить",
    "mgr.reassign": "Переназначить",
    "mgr.escalate": "Эскалировать",
    "mgr.slaCompliance": "Соблюдение SLA",
    "mgr.avgWaitTime": "Среднее время ожидания",
    "mgr.radLoad": "Нагрузка на радиологов",
    "mgr.unassigned": "Не назначен",
    "mgr.assignedTo": "Назначено",
    "mgr.radiologist": "Радиолог",
    "mgr.assignRadiologistTitle": "Назначить радиолога",
    "mgr.selectRadiologist": "Выберите радиолога",
    "mgr.escalationSuccess": "Приоритет успешно повышен.",
    "mgr.assignSuccess": "Радиолог успешно назначен.",
    "mgr.noQueuedItems": "Нет активных записей в очереди.",

    // Finance Module
    "fin.title": "Финансы клиники",
    "fin.totalCharged": "Всего начислено",
    "fin.totalPaid": "Всего выплачено",
    "fin.currentDebts": "Текущие долги",
    "fin.chargeByRole": "Начисления по ролям",
    "fin.statementRegistry": "Реестр начислений",
    "fin.makePayout": "Произвести выплату",
    "fin.exportCsv": "Экспорт в CSV",
    "fin.service": "Услуга / Правило",
    "fin.creditedTo": "Начислено",
    "fin.amount": "Сумма",
    "fin.date": "Дата",
    "general.finances": "Финансы",

    // SuperAdmin Module
    "sa.overview": "Обзор системы",
    "sa.forecasts": "Прогнозы",
    "sa.policies": "Системные политики",
    "sa.totalPatients": "Всего пациентов сегодня",
    "sa.systemRevenue": "Выручка системы",
    "sa.avgRadLoad": "Средняя нагрузка на радиологов",
    "sa.activeUsers": "Активные пользователи",
    "sa.nextMonthRevenue": "Прогноз выручки на след. месяц",
    "sa.patientGrowth": "Рост числа пациентов",
    "sa.policyName": "Название политики",
    "sa.value": "Значение",
    "sa.apply": "Применить изменения",
    "sa.broadcast": "Отправить уведомление",
    "sa.changesApplied": "Изменения успешно применены!",
    
    // Rules Engine Module
    "rules.integrations": "Интеграции",
    "rules.queue": "Логика очереди",
    "rules.sla": "Политика SLA",
    "rules.validate": "Проверить JSON",
    "rules.apply": "Применить изменения",
    "rules.valid": "JSON корректен.",
    "rules.invalid": "Некорректный JSON:",
    "rules.saved": "Правило успешно сохранено!",
    "rules.editorTitle": "Содержимое правила (JSON)",

    // Bonus & SLA Module
    "bonus.slaTimings": "Целевое время SLA",
    "bonus.bonusRules": "Правила бонусных баллов",
    "bonus.dryRun": "Симуляция и перерасчет",
    "bonus.targetMinutes": "Цель (минуты)",
    "bonus.points": "Баллы",
    "bonus.splits": "Распределение",
    "bonus.runSimulation": "Запустить симуляцию",
    "bonus.simulationResults": "Результаты симуляции",
    "bonus.saveChanges": "Сохранить изменения",
    "bonus.settingsUpdated": "Настройки успешно обновлены!",
    "bonus.affectedItems": "Затронуто записей",
    "bonus.totalBonusChange": "Изменение бонусов",
    "bonus.potentialBreaches": "Потенциальные нарушения SLA",
    "bonus.previousTotal": "Предыдущая сумма",
    "bonus.newTotal": "Новая сумма",

    // Language Manager Module
    "langMgr.key": "Ключ",
    "langMgr.save": "Сохранить изменения",
    "langMgr.checkCoverage": "Проверить покрытие",
    "langMgr.import": "Импорт JSON",
    "langMgr.export": "Экспорт JSON",
    "langMgr.coverageReport": "Отчет о покрытии",
    "langMgr.totalKeys": "Всего уникальных ключей",
    "langMgr.keys": "ключей",
    "langMgr.missingKeys": "Отсутствующие ключи",
    "langMgr.noMissing": "Все ключи на месте.",
    "langMgr.changesSaved": "Изменения успешно сохранены!",

    // RBAC Module
    "rbac.userManagement": "Управление пользователями",
    "rbac.permissionManagement": "Управление разрешениями",
    "rbac.user": "Пользователь",
    "rbac.email": "Email",
    "rbac.roles": "Роли",
    "rbac.manageRoles": "Управлять ролями",
    "rbac.permission": "Разрешение",
    "rbac.enabled": "Включено",
    "rbac.feature": "Функция",
    "rbac.canUseAiSummary": "Может использовать ИИ-сводку",
    "rbac.canManageDicomPolicies": "Может управлять политиками DICOM",
    "rbac.canUploadDicom": "Может загружать DICOM/документы",
    "rbac.canViewDicom": "Может просматривать DICOM/документы",
    "rbac.canAccessMedRep": "Может получить доступ к интерфейсу медпреда",
    "rbac.canAccessClinicAdmin": "Может получить доступ к админ-панели клиники", // New permission translation
    "rbac.canManageRooms": "Может управлять кабинетами и расписаниями", // New permission translation
    "rbac.canManageTariffs": "Может управлять тарифами и контрактами", // New permission translation
    "rbac.canManageClinicSettings": "Может управлять настройками клиники", // New permission translation
    "rbac.changesSaved": "Изменения успешно сохранены.",
    
    // DICOM Hub Module
    "dicomhub.title": "DICOM-хаб",
    "dicomhub.studyFiles": "Файлы исследований",
    "dicomhub.accessPolicies": "Политики доступа",
    "dicomhub.studyIdInput": "Введите ID исследования",
    "dicomhub.fileList": "Файлы для исследования {{studyId}}",
    "dicomhub.fileName": "Имя файла",
    "dicomhub.fileType": "Тип",
    "dicomhub.fileSize": "Размер (МБ)",
    "dicomhub.uploadedAt": "Загружено",
    "dicomhub.signedUrl": "Подписанная ссылка",
    "dicomhub.status": "Статус",
    "dicomhub.uploadFile": "Загрузить файл",
    "dicomhub.revokeLink": "Отменить ссылку",
    "dicomhub.uploadNewFile": "Загрузить новый файл",
    "dicomhub.policySaved": "Политики успешно сохранены!",
    "dicomhub.noFiles": "Файлы для этого исследования не найдены.",
    "dicomhub.noPolicies": "Политики не определены.",
    "dicomhub.role": "Роль",
    "dicomhub.canView": "Может просматривать",
    "dicomhub.canUpload": "Может загружать",
    "dicomhub.savePolicies": "Сохранить политики",
    "dicomhub.linkRevoked": "Ссылка отменена",
    "dicomhub.uploadSuccess": "Файл успешно загружен!",
    "dicomhub.uploadError": "Ошибка при загрузке файла.",
    "dicomhub.revokeConfirm": "Вы уверены, что хотите отозвать эту ссылку? Это действие необратимо.",
    "dicomhub.revokeSuccess": "Ссылка успешно отозвана!",
    "dicomhub.revokeError": "Ошибка при отзыве ссылки.",
    "dicomhub.fileUrl": "URL файла",
    "dicomhub.view": "Просмотреть",
    "dicomhub.active": "Активный",
    "dicomhub.revoked": "Отозвано",
    "dicomhub.uploadDicom": "Загрузить DICOM",
    "dicomhub.uploadDocument": "Загрузить Документ",

    // MedRep Interface Module
    "medrep.title": "MedRep Interface",
    "medrep.overview": "Overview",
    "medrep.kpis": "Key Performance Indicators",
    "medrep.referralFunnel": "Referral Funnel",
    "medrep.planFact": "Plan / Actual",
    "medrep.tasks": "Tasks",
    "medrep.chats": "Chats",
    "medrep.addTask": "Add Task",
    "medrep.completeTask": "Complete",
    "medrep.openChat": "Open Chat",
    "medrep.newTaskTitle": "Task Title",
    "medrep.dueDate": "Due Date",
    "medrep.clinic": "Related Clinic (Optional)",
    "medrep.noKpis": "No KPI data available for this period.",
    "medrep.noTasks": "No tasks for this medical representative.",
    "medrep.noChats": "No active chats.",
    "medrep.taskStatus.todo": "To Do",
    "medrep.taskStatus.doing": "Doing",
    "medrep.taskStatus.done": "Done",
    "medrep.taskAddedSuccess": "Task added successfully!",
    "medrep.taskUpdatedSuccess": "Task updated successfully!",
    "medrep.taskActionError": "Error performing task action.",
    "medrep.chatTopic": "Chat Topic",
    "medrep.lastMessage": "Last Message",
    "medrep.sendMessage": "Send Message",
    "medrep.chatInputPlaceholder": "Type your message...",
    "medrep.noMessages": "No messages in this chat yet.",
    "medrep.chatPanelTitle": "Chat with {{topic}}",
    "medrep.selectChatPrompt": "Select a chat to view messages.",
    "medrep.newChatPrompt": "Create new chat",

    // Clinic Module
    "clinic.title": "Управление Клиникой",
    "clinic.clinics": "Клиники",
    "clinic.rooms": "Кабинеты и Расписание",
    "clinic.tariffs": "Тарифы и Контракты",
    "clinic.settings": "Настройки",
    "clinic.createClinic": "Создать Клинику",
    "clinic.editClinic": "Редактировать Клинику",
    "clinic.suspendClinic": "Приостановить Клинику",
    "clinic.name": "Название Клиники",
    "clinic.code": "Код",
    "clinic.address": "Адрес",
    "clinic.phones": "Телефоны",
    "clinic.email": "Email",
    "clinic.geo": "Геоположение",
    "clinic.status": "Статус",
    "clinic.createdAt": "Создано",
    "clinic.active": "Активна",
    "clinic.suspended": "Приостановлена",
    "clinic.noClinics": "Клиники не найдены.",
    "clinic.selectClinic": "Выберите Клинику",
    "clinic.addPhone": "Добавить Телефон",
    "clinic.today": "Сегодня",
    "clinic.horizon": "Горизонт (3/7/30 дней)",
    "clinic.compare": "Сравнение Кабинетов",
    "clinic.roomName": "Название Кабинета",
    "clinic.modality": "Модальность",
    "clinic.deviceIds": "Устройства",
    "clinic.capacityPerHour": "Пациентов в час",
    "clinic.workHours": "Рабочие Часы",
    "clinic.tags": "Теги",
    "clinic.addRoom": "Добавить Кабинет",
    "clinic.editRoom": "Редактировать Кабинет",
    "clinic.roomStatus": "Статус Кабинета",
    "clinic.status.up": "Работает",
    "clinic.status.down": "Не работает",
    "clinic.status.maintenance": "Ремонт",
    "clinic.nextServiceAt": "След. Обслуживание",
    "clinic.addSlot": "Добавить Слот",
    "clinic.editWorkHours": "Редактировать Рабочие Часы",
    "clinic.setBlackout": "Установить Простой",
    "clinic.removeBlackout": "Удалить Простой",
    "clinic.capacity": "Емкость",
    "clinic.booked": "Записано",
    "clinic.free": "Свободно",
    "clinic.loadPct": "Загрузка %",
    "clinic.noSchedules": "Расписание на этот день не найдено.",
    "clinic.saveCapacity": "Сохранить Емкость",
    "clinic.selectPeriod": "Выберите Период",
    "clinic.avgLoadPct": "Средняя Загрузка %",
    "clinic.totalBooked": "Всего Записано",
    "clinic.totalCapacity": "Общая Емкость",
    "clinic.noCompareData": "Нет данных для сравнения.",
    "clinic.tariffTitle": "Название Услуги",
    "clinic.serviceCode": "Код Услуги",
    "clinic.price": "Цена",
    "clinic.currency": "Валюта",
    "clinic.effectiveFrom": "Действует с",
    "clinic.effectiveTo": "Действует до",
    "clinic.addTariff": "Добавить Тариф",
    "clinic.editTariff": "Редактировать Тариф",
    "clinic.archiveTariff": "Архивировать Тариф",
    "clinic.noTariffs": "Тарифы не найдены.",
    "clinic.contractPayer": "Плательщик",
    "clinic.contractValidFrom": "Действует с",
    "clinic.contractValidTo": "Действует до",
    "clinic.addContract": "Добавить Контракт",
    "clinic.editContract": "Редактировать Контракт",
    "clinic.noContracts": "Контракты не найдены.",
    "clinic.policyName": "Название Политики",
    "clinic.policyValue": "Значение",
    "clinic.policyDescription": "Описание",
    "clinic.saveSettings": "Сохранить Настройки",
    "clinic.settingsSaved": "Настройки успешно сохранены!",
    "clinic.blackoutReason": "Причина простоя",
    "clinic.blackoutStart": "Время начала",
    "clinic.blackoutEnd": "Время окончания",
    "clinic.confirmDelete": "Вы уверены, что хотите это удалить?",
    "clinic.clinicCreatedSuccess": "Клиника успешно создана!",
    "clinic.clinicUpdatedSuccess": "Клиника успешно обновлена!",
    "clinic.clinicSuspendedSuccess": "Статус клиники успешно обновлен!",
    "clinic.roomCreatedSuccess": "Кабинет успешно создан!",
    "clinic.roomUpdatedSuccess": "Кабинет успешно обновлен!",
    "clinic.roomStatusUpdatedSuccess": "Статус кабинета успешно обновлен!",
    "clinic.slotAddedSuccess": "Слоты успешно добавлены!",
    "clinic.blackoutAddedSuccess": "Период простоя добавлен успешно!",
    "clinic.blackoutRemovedSuccess": "Простой успешно удален!",
    "clinic.tariffCreatedSuccess": "Тариф успешно создан!",
    "clinic.tariffUpdatedSuccess": "Тариф успешно обновлен!",
    "clinic.contractCreatedSuccess": "Контракт успешно создан!",
    "clinic.contractUpdatedSuccess": "Контракт успешно обновлен!",
    "clinic.errorFetching": "Ошибка получения данных.",
    "clinic.errorSaving": "Ошибка сохранения данных.",
    "clinic.overlappingSlotsError": "Обнаружены пересекающиеся слоты. Пожалуйста, скорректируйте.",


    // Queue Statuses
    queued: 'В очереди',
    in_progress: 'В процессе',
    described: 'Описано',
    no_show: 'Неявка',

     // Roles - Moved into a nested 'roles' object to avoid top-level key collisions
    roles: {
      [UserRole.SuperAdmin]: 'СуперАдмин',
      [UserRole.Admin]: 'Админ',
      [UserRole.Manager]: 'Менеджер',
      [UserRole.Radiologist]: 'Радиолог',
      [UserRole.Referrer]: 'Направляющий',
      [UserRole.Patient]: 'Пациент', // This is now the canonical way to get 'Пациент' translation
      [UserRole.Finance]: 'Финансы',
      [UserRole.MrtOperator]: 'Оператор МРТ',
      [UserRole.Reception]: 'Регистратура',
      [UserRole.MedRep]: 'Медицинский представитель',
      [UserRole.ClinicAdmin]: 'Админ Клиники', // New role translation
    },

    // Modalities
    [RoomModality.MRI]: "МРТ",
    [RoomModality.CT]: "КТ",
    [RoomModality.XRAY]: "Рентген",
    [RoomModality.US]: "УЗИ",

    // Room Statuses
    [RoomStatus.Up]: "Работает",
    [RoomStatus.Down]: "Не работает",
    [RoomStatus.Maintenance]: "Ремонт",

    // Clinic Statuses
    [ClinicStatus.Active]: "Активна",
    [ClinicStatus.Suspended]: "Приостановлена",

    // Payer Types
    [PayerType.Self]: "Своя оплата",
    [PayerType.Insurance]: "Страховая",
    [PayerType.Corporate]: "Корпоративная",


    // Modules
    [Module.ReceptionQueue]: 'Регистратура и очередь',
    [Module.MrtRoom]: 'Кабинет МРТ',
    [Module.RadiologyWorkbench]: 'АРМ Радиолога',
    [Module.ReferrerPortal]: 'Портал направляющего',
    [Module.PatientApp]: 'Приложение пациента',
    [Module.ManagerPanel]: 'Панель менеджера',
    [Module.ClinicFinance]: 'Финансы клиники', // This evaluates to 'clinicFinance'
    [Module.SuperAdmin]: 'Панель СуперАдмина',
    [Module.RoleAccess]: 'Управление ролями и доступом',
    [Module.RulesEngine]: 'Редактор правил',
    [Module.BonusSla]: 'Управление бонусами и SLA',
    [Module.LanguageManager]: 'Управление языками',
    [Module.ModuleConstructor]: 'Конструктор модулей',
    [Module.TestSandbox]: 'Тестовая среда',
    [Module.DicomHub]: 'DICOM-хаб',
    [Module.MedRepInterface]: 'Интерфейс МедПреда',
    [Module.Clinic]: 'Управление Клиникой', // New module translation
  },
  // UZ and KK translations are omitted for brevity but would follow the same structure
  [Language.UZ]: { appName: 'MedMIS Core 2.0',
    // Clinic Module
    "clinic.title": "Klinika boshqaruvi",
    "clinic.clinics": "Klinikalar",
    "clinic.rooms": "Xonalar va jadvallar",
    "clinic.tariffs": "Tariflar va shartnomalar",
    "clinic.settings": "Sozlamalar",
    "clinic.createClinic": "Klinika yaratish",
    "clinic.editClinic": "Klinikani tahrirlash",
    "clinic.suspendClinic": "Klinikani to'xtatish",
    "clinic.name": "Klinika nomi",
    "clinic.code": "Kodi",
    "clinic.address": "Manzil",
    "clinic.phones": "Telefonlar",
    "clinic.email": "Elektron pochta",
    "clinic.geo": "Geo joylashuvi",
    "clinic.status": "Holat",
    "clinic.createdAt": "Yaratilgan sana",
    "clinic.active": "Faol",
    "clinic.suspended": "To'xtatilgan",
    "clinic.noClinics": "Klinikalar topilmadi.",
    "clinic.selectClinic": "Klinikani tanlang",
    "clinic.addPhone": "Telefon qo'shish",
    "clinic.today": "Bugun",
    "clinic.horizon": "Ufq (3/7/30 kun)",
    "clinic.compare": "Xonalarni taqqoslash",
    "clinic.roomName": "Xona nomi",
    "clinic.modality": "Modalite",
    "clinic.deviceIds": "Qurilmalar",
    "clinic.capacityPerHour": "Soatiga bemorlar",
    "clinic.workHours": "Ish soatlari",
    "clinic.tags": "Teglar",
    "clinic.addRoom": "Xona qo'shish",
    "clinic.editRoom": "Xonani tahrirlash",
    "clinic.roomStatus": "Xona holati",
    "clinic.status.up": "Ishlayapti",
    "clinic.status.down": "Ishlamayapti",
    "clinic.status.maintenance": "Ta'mirlash",
    "clinic.nextServiceAt": "Keyingi xizmat ko'rsatish",
    "clinic.addSlot": "Slot qo'shish",
    "clinic.editWorkHours": "Ish soatlarini tahrirlash",
    "clinic.setBlackout": "Qora vaqt o'rnatish",
    "clinic.removeBlackout": "Qora vaqtni olib tashlash",
    "clinic.capacity": "Sig'im",
    "clinic.booked": "Band qilingan",
    "clinic.free": "Bo'sh",
    "clinic.loadPct": "Yuklanish %",
    "clinic.noSchedules": "Bu kun uchun jadval topilmadi.",
    "clinic.saveCapacity": "Sig'imni saqlash",
    "clinic.selectPeriod": "Davrni tanlang",
    "clinic.avgLoadPct": "O'rtacha yuklanish %",
    "clinic.totalBooked": "Jami band qilingan",
    "clinic.totalCapacity": "Jami sig'im",
    "clinic.noCompareData": "Taqqoslash uchun ma'lumot yo'q.",
    "clinic.tariffTitle": "Xizmat nomi",
    "clinic.serviceCode": "Xizmat kodi",
    "clinic.price": "Narx",
    "clinic.currency": "Valyuta",
    "clinic.effectiveFrom": "Amal qilish muddati (dan)",
    "clinic.effectiveTo": "Amal qilish muddati (gacha)",
    "clinic.addTariff": "Tarif qo'shish",
    "clinic.editTariff": "Tarifni tahrirlash",
    "clinic.archiveTariff": "Tarifni arxivlash",
    "clinic.noTariffs": "Tariflar topilmadi.",
    "clinic.contractPayer": "To'lovchi",
    "clinic.contractValidFrom": "Amal qilish muddati (dan)",
    "clinic.contractValidTo": "Amal qilish muddati (gacha)",
    "clinic.addContract": "Shartnoma qo'shish",
    "clinic.editContract": "Shartnomani tahrirlash",
    "clinic.noContracts": "Shartnomalar topilmadi.",
    "clinic.policyName": "Siyosat nomi",
    "clinic.policyValue": "Qiymat",
    "clinic.policyDescription": "Tavsif",
    "clinic.saveSettings": "Sozlamalarni saqlash",
    "clinic.settingsSaved": "Sozlamalar muvaffaqiyatli saqlandi!",
    "clinic.blackoutReason": "Qora vaqt sababi",
    "clinic.blackoutStart": "Boshlanish vaqti",
    "clinic.blackoutEnd": "Tugash vaqti",
    "clinic.confirmDelete": "Haqiqatan ham o'chirmoqchimisiz?",
    "clinic.clinicCreatedSuccess": "Klinika muvaffaqiyatli yaratildi!",
    "clinic.clinicUpdatedSuccess": "Klinika muvaffaqiyatli yangilandi!",
    "clinic.clinicSuspendedSuccess": "Klinika holati muvaffaqiyatli yangilandi!",
    "clinic.roomCreatedSuccess": "Xona muvaffaqiyatli yaratildi!",
    "clinic.roomUpdatedSuccess": "Xona muvaffaqiyatli yangilandi!",
    "clinic.roomStatusUpdatedSuccess": "Xona holati muvaffaqiyatli yangilandi!",
    "clinic.slotAddedSuccess": "Slotlar muvaffaqiyatli qo'shildi!",
    "clinic.blackoutAddedSuccess": "Qora vaqt muvaffaqiyatli qo'shildi!",
    "clinic.blackoutRemovedSuccess": "Qora vaqt muvaffaqiyatli olib tashlandi!",
    "clinic.tariffCreatedSuccess": "Tarif muvaffaqiyatli yaratildi!",
    "clinic.tariffUpdatedSuccess": "Tarif muvaffaqiyatli yangilandi!",
    "clinic.contractCreatedSuccess": "Shartnoma muvaffaqiyatli yaratildi!",
    "clinic.contractUpdatedSuccess": "Shartnoma muvaffaqiyatli yangilandi!",
    "clinic.errorFetching": "Ma'lumotlarni olishda xato.",
    "clinic.errorSaving": "Ma'lumotlarni saqlashda xato.",
    "clinic.overlappingSlotsError": "Bir-biriga mos keladigan slotlar aniqlandi. Iltimos, sozlang.",
    roles: {
        [UserRole.SuperAdmin]: 'SuperAdmin',
        [UserRole.Admin]: 'Admin',
        [UserRole.Manager]: 'Menejer',
        [UserRole.Radiologist]: 'Radiolog',
        [UserRole.Referrer]: 'Yo‘naltiruvchi',
        [UserRole.Patient]: 'Bemor',
        [UserRole.Finance]: 'Moliya',
        [UserRole.MrtOperator]: 'MRT Operatori',
        [UserRole.Reception]: 'Resepsiyon',
        [UserRole.MedRep]: 'Tibbiy vakil',
        [UserRole.ClinicAdmin]: 'Klinika Admini',
    },
    [Module.ReceptionQueue]: 'Resepsiyon va navbat',
    [Module.MrtRoom]: 'MRT xonasi',
    [Module.RadiologyWorkbench]: 'Radiologiya ish o‘rni',
    [Module.ReferrerPortal]: 'Yo‘naltiruvchi portali',
    [Module.PatientApp]: 'Bemor ilovasi',
    [Module.ManagerPanel]: 'Menejer paneli',
    [Module.ClinicFinance]: 'Klinika moliyasi',
    [Module.SuperAdmin]: 'SuperAdmin boshqaruv paneli',
    [Module.RoleAccess]: 'Rol va kirish huquqi boshqaruvi',
    [Module.RulesEngine]: 'Qoidalar dvigateli',
    [Module.BonusSla]: 'Bonus va SLA boshqaruvi',
    [Module.LanguageManager]: 'Til boshqaruvi',
    [Module.ModuleConstructor]: 'Modul konstruktori',
    [Module.TestSandbox]: 'Sinov maydoni',
    [Module.DicomHub]: 'DICOM markazi',
    [Module.MedRepInterface]: 'MedRep interfeysi',
    [Module.Clinic]: 'Klinika boshqaruvi',
  },
  [Language.KK]: { appName: 'MedMIS Core 2.0',
    // Clinic Module
    "clinic.title": "Клиниканы басқару",
    "clinic.clinics": "Клиникалар",
    "clinic.rooms": "Бөлмелер және кестелер",
    "clinic.tariffs": "Тарифтер мен келісімшарттар",
    "clinic.settings": "Параметрлер",
    "clinic.createClinic": "Клиника құру",
    "clinic.editClinic": "Клиниканы өңдеу",
    "clinic.suspendClinic": "Клиниканы тоқтата тұру",
    "clinic.name": "Клиника атауы",
    "clinic.code": "Коды",
    "clinic.address": "Мекенжайы",
    "clinic.phones": "Телефондар",
    "clinic.email": "Электрондық пошта",
    "clinic.geo": "Гео орналасуы",
    "clinic.status": "Мәртебесі",
    "clinic.createdAt": "Құрылған күні",
    "clinic.active": "Белсенді",
    "clinic.suspended": "Тоқтатылған",
    "clinic.noClinics": "Клиникалар табылмады.",
    "clinic.selectClinic": "Клиниканы таңдаңыз",
    "clinic.addPhone": "Телефон қосу",
    "clinic.today": "Бүгін",
    "clinic.horizon": "Көкжиек (3/7/30 күн)",
    "clinic.compare": "Бөлмелерді салыстыру",
    "clinic.roomName": "Бөлме атауы",
    "clinic.modality": "Модальділік",
    "clinic.deviceIds": "Құрылғылар",
    "clinic.capacityPerHour": "Сағатына пациенттер",
    "clinic.workHours": "Жұмыс уақыты",
    "clinic.tags": "Тегтер",
    "clinic.addRoom": "Бөлме қосу",
    "clinic.editRoom": "Бөлмені өңдеу",
    "clinic.roomStatus": "Бөлме мәртебесі",
    "clinic.status.up": "Жұмыс істеп тұр",
    "clinic.status.down": "Жұмыс істемейді",
    "clinic.status.maintenance": "Техникалық қызмет көрсету",
    "clinic.nextServiceAt": "Келесі қызмет көрсету",
    "clinic.addSlot": "Слот қосу",
    "clinic.editWorkHours": "Жұмыс уақытын өңдеу",
    "clinic.setBlackout": "Қараңғы уақыт орнату",
    "clinic.removeBlackout": "Қараңғы уақытты жою",
    "clinic.capacity": "Сыйымдылық",
    "clinic.booked": "Брондалған",
    "clinic.free": "Бос",
    "clinic.loadPct": "Жүктеме %",
    "clinic.noSchedules": "Бұл күнге кесте табылмады.",
    "clinic.saveCapacity": "Сыйымдылықты сақтау",
    "clinic.selectPeriod": "Кезеңді таңдаңыз",
    "clinic.avgLoadPct": "Орт. жүктеме %",
    "clinic.totalBooked": "Жалпы брондалған",
    "clinic.totalCapacity": "Жалпы сыйымдылық",
    "clinic.noCompareData": "Салыстыру деректері жоқ.",
    "clinic.tariffTitle": "Қызмет атауы",
    "clinic.serviceCode": "Қызмет коды",
    "clinic.price": "Бағасы",
    "clinic.currency": "Валюта",
    "clinic.effectiveFrom": "Басталу күні",
    "clinic.effectiveTo": "Аяқталу күні",
    "clinic.addTariff": "Тариф қосу",
    "clinic.editTariff": "Тарифті өңдеу",
    "clinic.archiveTariff": "Тарифті мұрағаттау",
    "clinic.noTariffs": "Тарифтер табылмады.",
    "clinic.contractPayer": "Төлеуші",
    "clinic.contractValidFrom": "Басталу күні",
    "clinic.contractValidTo": "Аяқталу күні",
    "clinic.addContract": "Келісімшарт қосу",
    "clinic.editContract": "Келісімшартты өңдеу",
    "clinic.noContracts": "Келісімшарттар табылмады.",
    "clinic.policyName": "Саясат атауы",
    "clinic.policyValue": "Мәні",
    "clinic.policyDescription": "Сипаттамасы",
    "clinic.saveSettings": "Параметрлерді сақтау",
    "clinic.settingsSaved": "Параметрлер сәтті сақталды!",
    "clinic.blackoutReason": "Қараңғы уақыт себебі",
    "clinic.blackoutStart": "Басталу уақыты",
    "clinic.blackoutEnd": "Аяқталу уақыты",
    "clinic.confirmDelete": "Мұны жойғыңыз келетініне сенімдісіз бе?",
    "clinic.clinicCreatedSuccess": "Клиника сәтті құрылды!",
    "clinic.clinicUpdatedSuccess": "Клиника сәтті жаңартылды!",
    "clinic.clinicSuspendedSuccess": "Клиника мәртебесі сәтті жаңартылды!",
    "clinic.roomCreatedSuccess": "Бөлме сәтті құрылды!",
    "clinic.roomUpdatedSuccess": "Бөлме сәтті жаңартылды!",
    "clinic.roomStatusUpdatedSuccess": "Бөлме мәртебесі сәтті жаңартылды!",
    "clinic.slotAddedSuccess": "Слоттар сәтті қосылды!",
    "clinic.blackoutAddedSuccess": "Қараңғы уақыт кезеңі сәтті қосылды!",
    "clinic.blackoutRemovedSuccess": "Қараңғы уақыт сәтті жойылды!",
    "clinic.tariffCreatedSuccess": "Тариф сәтті құрылды!",
    "clinic.tariffUpdatedSuccess": "Тариф сәтті жаңартылды!",
    "clinic.contractCreatedSuccess": "Келісімшарт сәтті құрылды!",
    "clinic.contractUpdatedSuccess": "Келісімшарт сәтті жаңартылды!",
    "clinic.errorFetching": "Деректерді алу қатесі.",
    "clinic.errorSaving": "Деректерді сақтау қатесі.",
    "clinic.overlappingSlotsError": "Бөлмелерде қабаттасулар табылды. Реттеңіз.",
    roles: {
        [UserRole.SuperAdmin]: 'Суперадмин',
        [UserRole.Admin]: 'Админ',
        [UserRole.Manager]: 'Менеджер',
        [UserRole.Radiologist]: 'Рентгенолог',
        [UserRole.Referrer]: 'Жолдама беруші',
        [UserRole.Patient]: 'Пациент',
        [UserRole.Finance]: 'Қаржы',
        [UserRole.MrtOperator]: 'МРТ операторы',
        [UserRole.Reception]: 'Ресепшн',
        [UserRole.MedRep]: 'Медициналық өкіл',
        [UserRole.ClinicAdmin]: 'Клиника әкімшісі',
    },
    [Module.ReceptionQueue]: 'Ресепшн және кезек',
    [Module.MrtRoom]: 'МРТ бөлмесі',
    [Module.RadiologyWorkbench]: 'Рентгенологтың жұмыс орны',
    [Module.ReferrerPortal]: 'Жолдама беруші порталы',
    [Module.PatientApp]: 'Пациент қосымшасы',
    [Module.ManagerPanel]: 'Менеджер панелі',
    [Module.ClinicFinance]: 'Клиника қаржысы',
    [Module.SuperAdmin]: 'Суперадмин бақылау тақтасы',
    [Module.RoleAccess]: 'Рөлге және рұқсатқа қол жеткізу менеджері',
    [Module.RulesEngine]: 'Ережелер қозғалтқышы',
    [Module.BonusSla]: 'Бонус және SLA бақылауы',
    [Module.LanguageManager]: 'Тіл менеджері',
    [Module.ModuleConstructor]: 'Модуль конструкторы',
    [Module.TestSandbox]: 'Тест құмсалғышы',
    [Module.DicomHub]: 'DICOM хабы',
    [Module.MedRepInterface]: 'MedRep интерфейсі',
    [Module.Clinic]: 'Клиниканы басқару',
  },
};

export const ALL_ROLES: UserRole[] = Object.values(UserRole);
export const ALL_LANGUAGES: Language[] = [Language.EN, Language.RU, Language.UZ, Language.KK];
export const ALL_PRIORITIES: Priority[] = [Priority.SR, Priority.STD, Priority.PLN];
export const ALL_ROOM_MODALITIES: RoomModality[] = Object.values(RoomModality);
export const ALL_PAYER_TYPES: PayerType[] = Object.values(PayerType);


export const ROLE_MODULES: Record<UserRole, Module[]> = {
    [UserRole.Reception]: [Module.ReceptionQueue],
    [UserRole.Referrer]: [Module.ReferrerPortal],
    [UserRole.MrtOperator]: [Module.MrtRoom],
    [UserRole.Radiologist]: [Module.RadiologyWorkbench, Module.DicomHub],
    [UserRole.Patient]: [Module.PatientApp],
    [UserRole.Manager]: [Module.ManagerPanel, Module.ClinicFinance, Module.BonusSla, Module.ReceptionQueue, Module.Clinic],
    [UserRole.Finance]: [Module.ClinicFinance],
    [UserRole.Admin]: [Module.RoleAccess, Module.LanguageManager, Module.Clinic],
    [UserRole.MedRep]: [Module.MedRepInterface],
    [UserRole.ClinicAdmin]: [Module.Clinic, Module.ManagerPanel, Module.ClinicFinance], // New role module mapping
    [UserRole.SuperAdmin]: [
        Module.SuperAdmin,
        Module.RoleAccess,
        Module.RulesEngine,
        Module.BonusSla,
        Module.LanguageManager,
        Module.ModuleConstructor,
        Module.TestSandbox,
        Module.DicomHub,
        Module.ManagerPanel,
        Module.ClinicFinance,
        Module.MedRepInterface,
        Module.Clinic, // Add for SuperAdmin to access all
    ],
};
